/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Ozelogo.glb -o src/app/components/BackgroundComponent/Experience/models/Ozelogo.jsx --root public --types --shadows --keepnames --printwidth 120 --precision 3 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF, MeshTransmissionMaterial } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useControls } from "leva";

type GLTFResult = GLTF & {
  nodes: {
    Glass: THREE.Mesh;
    Logo: THREE.Mesh;
  };
  materials: {
    Glass: THREE.MeshStandardMaterial;
    Logo: THREE.MeshStandardMaterial;
  };
};

export function Ozelogo(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/models/Ozelogo.glb") as GLTFResult;

  // Move useControls outside the component or memoize it
  const transmissionConfig = useControls(
    "Glass",
    {
      transmission: { value: 1, min: 0, max: 1 },
      thickness: { value: 0.5, min: 0, max: 2 },
      roughness: { value: 0.2, min: 0, max: 1 },
      ior: { value: 1.5, min: 1, max: 2.3 },
      chromaticAberration: { value: 0.03, min: 0, max: 1 },
      anisotropicBlur: { value: 0.1, min: 0, max: 1 },
      distortion: { value: 0, min: 0, max: 1 },
      distortionScale: { value: 0.5, min: 0, max: 1 },
      temporalDistortion: { value: 0.0, min: 0, max: 1 },
      clearcoat: { value: 1, min: 0, max: 1 },
      attenuationDistance: { value: 0.5, min: 0, max: 2 },
      attenuationColor: "#ffffff",
      samples: { value: 6, min: 1, max: 32, step: 1 },
      resolution: { value: 256, min: 64, max: 2048, step: 64 },
    },
    { collapsed: true }
  );

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Glass"
        castShadow
        receiveShadow
        geometry={nodes.Glass.geometry}
      >
        <MeshTransmissionMaterial {...transmissionConfig} />
        <mesh
          name="Logo"
          castShadow
          receiveShadow
          geometry={nodes.Logo.geometry}
        >
          <meshPhysicalMaterial
            color="#ffffff"
            metalness={1}
            roughness={0.05}
            envMapIntensity={1}
            clearcoat={1}
            clearcoatRoughness={0.1}
          />
        </mesh>
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/Ozelogo.glb");
